drivers/misc/mediatek/pmic/mt6370/v1/mt6370_pmu_irq.c: Suppress unused variable warning
../drivers/misc/mediatek/pmic/mt6370/v1/mt6370_pmu_irq.c:196:5: error: variable 'irq_ind' set but not used [-Werror,-Wunused-but-set-variable]
        u8 irq_ind = 0, data[16] = { 0 }, mask[16] = {
           ^
1 error generated.